pipeline {
  agent any
  tools {
    nodejs '19.5.0'
  }

  options {
    timeout(time: 2, unit: 'MINUTES')
  }

  stages {
    stage('Install dependencies') {
      steps {
        bat 'cd jenkins_tests && npm i'
      }
    }
    stage('Run tests') {
      steps {
        bat 'cd jenkins_tests && npm t'
      }
    }
  }
}
